# Generated by Django 5.0.4 on 2024-04-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('SUSP', 'Suspense'), ('ACTION', 'Ação'), ('COMEDY', 'Comédia'), ('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('DOCUMENTARY', 'Documentário'), ('OTHERS', 'Outros')], max_length=30),
        ),
    ]
