# Generated by Django 5.0.4 on 2024-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('SUSP', 'Suspense'), ('ACTION', 'Ação'), ('COMEDY', 'Comédia'), ('DRAMA', 'Drama'), ('ROMANCE', 'Romance'), ('DOCUMENTARY', 'Documentário'), ('SCI-FI', 'Ficção Científica'), ('HORROR', 'Terror'), ('FANTASY', 'Fantasia'), ('ANIMATION', 'Animação'), ('CRIME', 'Crime'), ('THRILLER', 'Thriller'), ('ADVENTURE', 'Aventura'), ('FAMILY', 'Família'), ('MUSICAL', 'Musical')], max_length=30),
        ),
    ]
